"""AI Resume generation service."""
from typing import Optional

from app.core.config import settings

# Try to import OpenAI at module level
try:
    from openai import AsyncOpenAI
    OPENAI_AVAILABLE = True
except ImportError:
    OPENAI_AVAILABLE = False


class ResumeGeneratorService:
    """Service for generating tailored resumes using AI."""

    async def generate_resume(
        self,
        target_role: str,
        user_experience: str,
        user_skills: str,
        target_company: Optional[str] = None,
        job_description: Optional[str] = None,
        user_education: Optional[str] = None,
    ) -> str:
        """Generate a tailored resume using AI.

        Args:
            target_role: Target job role
            user_experience: User's work experience
            user_skills: User's skills
            target_company: Target company (optional)
            job_description: Job description to tailor for (optional)
            user_education: User's education (optional)

        Returns:
            Generated resume content in markdown format
        """
        # If OpenAI API key is configured, use it
        if settings.OPENAI_API_KEY:
            return await self._generate_with_openai(
                target_role,
                user_experience,
                user_skills,
                target_company,
                job_description,
                user_education,
            )

        # Otherwise, generate a template-based resume
        return self._generate_template_resume(
            target_role,
            user_experience,
            user_skills,
            target_company,
            job_description,
            user_education,
        )

    async def _generate_with_openai(
        self,
        target_role: str,
        user_experience: str,
        user_skills: str,
        target_company: Optional[str] = None,
        job_description: Optional[str] = None,
        user_education: Optional[str] = None,
    ) -> str:
        """Generate resume using OpenAI API."""
        if not OPENAI_AVAILABLE:
            return self._generate_template_resume(
                target_role,
                user_experience,
                user_skills,
                target_company,
                job_description,
                user_education,
            )
        
        try:
            client = AsyncOpenAI(api_key=settings.OPENAI_API_KEY)

            prompt = f"""Create a professional resume for a {target_role} position.

User's Experience:
{user_experience}

User's Skills:
{user_skills}

{f"Target Company: {target_company}" if target_company else ""}
{f"Education: {user_education}" if user_education else ""}

{f"Job Description to tailor for:{chr(10)}{job_description}" if job_description else ""}

Generate a well-formatted resume in markdown format that highlights relevant experience 
and skills for this role. Focus on achievements and quantifiable results."""

            response = await client.chat.completions.create(
                model="gpt-3.5-turbo",
                messages=[
                    {
                        "role": "system",
                        "content": "You are a professional resume writer. Create concise, impactful resumes.",
                    },
                    {"role": "user", "content": prompt},
                ],
                max_tokens=2000,
            )

            return response.choices[0].message.content

        except Exception as e:
            # Fall back to template if OpenAI fails
            return self._generate_template_resume(
                target_role,
                user_experience,
                user_skills,
                target_company,
                job_description,
                user_education,
            )

    def _generate_template_resume(
        self,
        target_role: str,
        user_experience: str,
        user_skills: str,
        target_company: Optional[str] = None,
        job_description: Optional[str] = None,
        user_education: Optional[str] = None,
    ) -> str:
        """Generate a template-based resume."""
        company_text = f" at {target_company}" if target_company else ""
        education_section = ""
        if user_education:
            education_section = f"""
## Education

{user_education}
"""

        resume = f"""# Professional Resume

## Objective

Seeking a position as **{target_role}**{company_text} where I can leverage my skills 
and experience to contribute to team success.

## Skills

{user_skills}

## Professional Experience

{user_experience}
{education_section}
---
*Resume generated by Job Search Automation Platform*
"""
        return resume


resume_generator_service = ResumeGeneratorService()
